version: 0.2

phases:
  install:
    commands:
      - npm install -g serverless
      - pip install boto3
  build:
    commands:
      - serverless deploy
  artifacts:
    files:
      - '**/*'
    base-directory: .serverless
